/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [],
  docs: [
    {
      type: 'category',
      label: '介绍',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'intro',
        },
      ],
    },
    {
      type: 'category',
      label: '模板语法',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'template',
        },
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'base',
    },
  ],
};

module.exports = sidebars;
