name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set branch name
      run: echo >>$GITHUB_ENV BRANCH_NAME=${GITHUB_REF#refs/heads/}
    - name: Echo branch name
      run: echo ${BRANCH_NAME}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - name: Check Branch
      id: check-branch
      run: |
          if [[ ${{ env.BRANCH_NAME }} =~ ^(master|release-next)$|^hotfix\/* ]]; then
              echo ::set-output name=match::true
          fi
    - uses: pnpm/action-setup@v2
      with:
        version: 6.25.0
    - run: npm run setup
    - run: npm run lint
    - run: npm run test
