name: Test docs

on:
  push:
    paths:
      - .github/workflows/doc-test.yml
      - website/**

jobs:
  deploy:
    name: Test docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
      - name: Build website
        run: pnpm build